// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6kt2R4iZwVpADT-xAk87K0wcwMzkWCOQ',
    appId: '1:1092006598794:web:42beca0eff5c982374b573',
    messagingSenderId: '1092006598794',
    projectId: 'flutterapp-e9970',
    authDomain: 'flutterapp-e9970.firebaseapp.com',
    storageBucket: 'flutterapp-e9970.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa69UcxCuXWlkYpgC15VWon30wu4SDWnc',
    appId: '1:1092006598794:android:31bd9b7d3fe046c774b573',
    messagingSenderId: '1092006598794',
    projectId: 'flutterapp-e9970',
    storageBucket: 'flutterapp-e9970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBePrLZNUshGR95i3JqrXDwQOVtu4ksOzw',
    appId: '1:1092006598794:ios:a393b7671bcca19574b573',
    messagingSenderId: '1092006598794',
    projectId: 'flutterapp-e9970',
    storageBucket: 'flutterapp-e9970.firebasestorage.app',
    iosClientId: '1092006598794-8hdgvv7c1f629bn6ffcbhs0jgljafikm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBePrLZNUshGR95i3JqrXDwQOVtu4ksOzw',
    appId: '1:1092006598794:ios:a393b7671bcca19574b573',
    messagingSenderId: '1092006598794',
    projectId: 'flutterapp-e9970',
    storageBucket: 'flutterapp-e9970.firebasestorage.app',
    iosClientId: '1092006598794-8hdgvv7c1f629bn6ffcbhs0jgljafikm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6kt2R4iZwVpADT-xAk87K0wcwMzkWCOQ',
    appId: '1:1092006598794:web:30f5ccfb4a77bb1774b573',
    messagingSenderId: '1092006598794',
    projectId: 'flutterapp-e9970',
    authDomain: 'flutterapp-e9970.firebaseapp.com',
    storageBucket: 'flutterapp-e9970.firebasestorage.app',
  );
}
